### ISSUE TITLE
Having issues installing with pip

### ISSUE THREAD

**Issue by agrayseal** [oliviermirat/ZebraZoom#103]
I'm trying to install this through pip on MacOS (M1) and get the following error:
[error.txt](https://github.com/oliviermirat/ZebraZoom/files/13065324/error.txt)
I ran `pip install zebrazoom` in a new conda env with python 3.8

Thank you in advance for any help!

**Comment by oliviermirat** [comment]
Have you tried to install with the installer: https://github.com/oliviermirat/ZebraZoom/releases/latest/download/ZebraZoom-macOS.zip ?
That would probably be the best option.

Otherwise, with the pip installation, it might be useful to update the version of pip installed on your computer. Or if that doesn't work, possibly the Python version. Indeed, it looks like it's trying to install an older version of numpy and is failing to do so, and updating pip and/or Python might help.

Please don't hesitate to let me know if you have any other questions,

Best,

Olivier
