### ISSUE TITLE
New functionality asked: set save path and load ZZ output from a specified folder

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#12]
Hi Olivier,

We discussed this a while back, but we never pursued. Now I am analysing a lot of videos and am looking to optimize data managment. I want to save the output of ZZ on our server, so I currently need to copy paste the ZZ output folder from the local ZZ_output folder to the server. I also need to keep a copy on the local folder in case I need to check something in the GUI afterwards.

My proposition to ease this practise is the following:

1) could we specify the savePath in the config file where the results of the analysis would be stored ?
2) when using the GUI function "Visualize ZebraZoom's output", could we add the possibility to load from another folder (exact same structure, just saved somewhere else) ? For example, when we click on "Visualize ZebraZoom's output", there could be another button after the list of available analysed files, that says "Load from specified path" which opens file explorer and we can enter the specified path ?

Let me know if it would be feasible, it would really help easing the data analysis process especially when dealing with large amounts of videos.

Thanks !

**Comment by oliviermirat** [comment]
Hi Mathilde,

I actually recently implemented a new function that I think should solve your requests. When loading ZebraZoom, instead of typing "python -m zebrazoom", you can now instead type "python -m zebrazoom selectZZoutput" this will prompt you to choose a folder (you can choose a folder either on your local machine or on the server) and that folder will be set as the default output folder. I think this solves your two requests, please let me know if it doesn't.

**Comment by mathildelpx** [comment]
Hi Olivier, that's perfect, solves everything !
Tested to run a video and open ZZoutput, everything worked perfectly.

Thank you very much!
