### ISSUE TITLE
Improving coordinates pre-selection for equally spaced wells

### ISSUE THREAD

**Issue by Maha314** [oliviermirat/ZebraZoom#33]
Hey Olivier,

Selecting coordinates for defining the ROI while using "equally spaced wells" option now requires us to select 'Next' button in the GUI after every coordinate selected. 

Problem:
Although it gives the flexibility to change the points incase it was selected wrongly, it makes it cumbersome while using batch processing in "Run ZebraZoom's tracking on several videos" as  we need to click 6 times instead of 3.

Proposed solution:
Can we maybe select all the points (three coordinates sequentially) and with the flexibility to move the points and click on  "NEXT" only once so it moves to the next step?

Thanks!

**Comment by oliviermirat** [comment]
Since the "equally spaced wells" option allows to visualize the reparation of wells after clicking on the three point (top left, top right and bottom left), I would suggest going one step further and simply removing the "Next" button altogether in this specific case (and in this specific case only).

**Comment by oliviermirat** [comment]
This should now be fixed in the latest version of ZebraZoom (1.32.11)
