### ISSUE TITLE
An error occurs during configuring

### ISSUE THREAD

**Issue by Monkiesh** [oliviermirat/ZebraZoom#93]
<img width="695" alt="image" src="https://github.com/oliviermirat/ZebraZoom/assets/116359136/2cdf6ea7-f07d-470c-b950-0b71f55da2eb">

I am trying to track a freely swimming zebra fish, but this occurred when I am doing the configuration.

Here is the config file.
[04_2023_06_17-14_52_36_unfinished.json.txt](https://github.com/oliviermirat/ZebraZoom/files/11778159/04_2023_06_17-14_52_36_unfinished.json.txt)

And my vedio:
https://github.com/oliviermirat/ZebraZoom/assets/116359136/6b4f85d6-dfe5-4042-9e4c-303839aba904

**Comment by oliviermirat** [comment]
Hello,

Currently videos with "white fish and black background" are not supported for configuration file creation for freely swimming fish (only videos with "black fish and white background" are supported). We could probably make that improvement sometime soon if you want us to. If so, please email me at info@zebrazoom.org

In the meantime, you can still use the following configuration file to track the video you sent:
{"extractAdvanceZebraParameters": 1, "headEmbeded": 0, "noWellDetection": 1, "nbWells": 1, "noBoutsDetection": 0, "noChecksForBoutSelectionInExtractParams": 1, "trackingPointSizeDisplay": 4, "validationVideoPlotHeading": 0, "nbAnimalsPerWell": 1, "minArea": 1205, "maxArea": 4821, "minAreaBody": 1205, "maxAreaBody": 4821, "headSize": 32, "minTailSize": 5, "maxTailSize": 219, "paramGaussianBlur": 65, "extractBackWhiteBackground": 1, "onlyTrackThisOneWell": -1, "reloadBackground": 0, "reloadWellPositions": 0, "adjustFreelySwimTracking": 0, "minPixelDiffForBackExtract": 20, "trackTail": 1, "adjustDetectMovWithRawVideo": 0, "thresForDetectMovementWithRawVideo": 28, "frameGapComparision": 3, "halfDiameterRoiBoutDetect": 114, "minNbPixelForDetectMovementWithRawVideo": 0, "saveAllDataEvenIfNotInBouts": 1, "invertBlackWhiteOnImages": 1}

It is working well on my computer:

![image](https://github.com/oliviermirat/ZebraZoom/assets/17452771/06b8b623-4d79-4948-89a3-9a9f107c7815)

Best Regards,

Olivier

**Comment by oliviermirat** [comment]
If you update to the latest version of ZebraZoom (1.33.30), you can now create a configuration file for your video.

When you are on this first page:

![image](https://github.com/oliviermirat/ZebraZoom/assets/17452771/0c2ae04d-67f2-4b9c-a168-c7742105fd10)

select the checkbox "Click here to start from a configuration file previously created (instead of from scratch)"

And choose the file "invertBlackWhiteOnImages.json", which you can also find here: https://github.com/oliviermirat/ZebraZoom/blob/master/zebrazoom/configuration/invertBlackWhiteOnImages.json

Then create a configuration file as you normally would and it should work. If it doesn't, just let me know.

Let me know if that works for you.

**Comment by Monkiesh** [comment]
Thanks a lot for your help!!!!!!!!!!!!!!!!!!!!!
Sorry for didn't reply in time. (I am busy preparing my final exam tomorrow)
It works very well for me now.

**Comment by oliviermirat** [comment]
I'm glad I could help!
Let me know if you need anything else.
Olivier
